import { Product } from "./types";

export const products: Product[] = [
  // ===== REAL PRODUCTS (from actual inventory photos) =====
  {
    id: "prod-001",
    slug: "lilly-pulitzer-sequin-floral-shift-dress",
    name: "Sequin Floral Shift Dress",
    brand: "Lilly Pulitzer",
    category: "Dresses",
    size: "6",
    condition: "NWT",
    price: 12800,
    description:
      "Stunning sequin shift dress with bold pink floral design on a black background. Bright green leaf and stem accents throughout. Fully sequined for maximum sparkle. Sleeveless with crew neckline. New with tags — never worn! A true showstopper for any special occasion.",
    images: [
      "/products/product-11.jpg",
      "/products/product-06.jpg",
      "/products/product-14.jpg",
      "/products/product-09.jpg",
      "/products/product-12.jpg",
    ],
    status: "available",
    featured: true,
    createdAt: "2026-04-14T00:00:00Z",
    updatedAt: "2026-04-14T00:00:00Z",
  },
  {
    id: "prod-002",
    slug: "lilly-pulitzer-tropical-print-dress-xxl",
    name: "Tropical Sea Life Print Dress",
    brand: "Lilly Pulitzer",
    category: "Dresses",
    size: "XXL",
    condition: "NWT",
    price: 8900,
    description:
      "Playful tropical print dress featuring whimsical sea-life motifs — shells, fish, and starfish — in pink, blue, and yellow on a crisp white background. Classic Lilly Pulitzer fun-in-the-sun style. New with tags!",
    images: [
      "/products/product-02.jpg",
      "/products/product-07.jpg",
      "/products/product-08.jpg",
    ],
    status: "available",
    featured: true,
    createdAt: "2026-04-14T00:00:00Z",
    updatedAt: "2026-04-14T00:00:00Z",
  },
  {
    id: "prod-003",
    slug: "lilly-pulitzer-red-textured-shift-dress",
    name: "Red Textured Shift Dress",
    brand: "Lilly Pulitzer",
    category: "Dresses",
    size: "12",
    condition: "NWT",
    price: 9800,
    description:
      "Elegant solid red shift dress in beautiful textured bouclé fabric. Features a sweet bow detail at the chest. Sleeveless and sophisticated — perfect for brunch, work, or a night out. New with tags!",
    images: [
      "/products/product-04.jpg",
      "/products/product-03.jpg",
      "/products/product-05.jpg",
      "/products/product-10.jpg",
      "/products/product-13.jpg",
    ],
    status: "available",
    featured: true,
    createdAt: "2026-04-14T00:00:00Z",
    updatedAt: "2026-04-14T00:00:00Z",
  },
  {
    id: "prod-004",
    slug: "lilly-pulitzer-white-textured-dress",
    name: "White Embossed Leaf Dress",
    brand: "Lilly Pulitzer",
    category: "Dresses",
    size: "4",
    condition: "NWT",
    price: 9500,
    description:
      "Sophisticated white dress with a gorgeous embossed leaf pattern texture. Clean, elegant, and incredibly versatile — dress it up or down. New with tags!",
    images: ["/products/product-16.jpg", "/products/product-15.jpg"],
    status: "available",
    featured: true,
    createdAt: "2026-04-14T00:00:00Z",
    updatedAt: "2026-04-14T00:00:00Z",
  },
  {
    id: "prod-005",
    slug: "lilly-pulitzer-sea-life-button-dress",
    name: "Sea Life Button-Front Dress",
    brand: "Lilly Pulitzer",
    category: "Dresses",
    size: "XXL",
    condition: "NWT",
    price: 8500,
    description:
      "Breezy button-front dress with elastic waist in a fun pastel sea-life print. Pink, blue, and yellow motifs on white background. Easy, comfortable style perfect for warm-weather days. New with tags!",
    images: ["/products/product-15.jpg"],
    status: "available",
    featured: false,
    createdAt: "2026-04-14T00:00:00Z",
    updatedAt: "2026-04-14T00:00:00Z",
  },

  // ===== DUMMY PRODUCTS (for demo/filter testing) =====
  {
    id: "prod-006",
    slug: "lilly-pulitzer-pink-flamingo-top",
    name: "Pink Flamingo Sleeveless Top",
    brand: "Lilly Pulitzer",
    category: "Tops",
    size: "M",
    condition: "Like New",
    price: 4500,
    description:
      "Adorable flamingo print sleeveless top in classic Lilly pink. Lightweight and breezy — perfect for summer days. Worn once, in excellent condition.",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-13T00:00:00Z",
    updatedAt: "2026-04-13T00:00:00Z",
  },
  {
    id: "prod-007",
    slug: "tory-burch-navy-blazer",
    name: "Classic Navy Blazer",
    brand: "Tory Burch",
    category: "Outerwear",
    size: "8",
    condition: "Gently Used",
    price: 7500,
    description:
      "Timeless navy blazer with gold button details. Slightly structured for a polished look. Minor wear consistent with gentle use — still in fantastic shape.",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
    updatedAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "prod-008",
    slug: "vineyard-vines-whale-shorts",
    name: "Whale Print Chino Shorts",
    brand: "Vineyard Vines",
    category: "Bottoms",
    size: "S",
    condition: "NWT",
    price: 3500,
    description:
      "Fun whale print shorts in coral and navy. Classic preppy style. Brand new with all tags attached!",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-11T00:00:00Z",
    updatedAt: "2026-04-11T00:00:00Z",
  },
  {
    id: "prod-009",
    slug: "lilly-pulitzer-gold-sandals",
    name: "Gold Metallic Sandals",
    brand: "Lilly Pulitzer",
    category: "Accessories",
    size: "8",
    condition: "NWOT",
    price: 5500,
    description:
      "Gorgeous gold metallic sandals that go with everything. New without tags — purchased but never worn outside. Perfect resort-ready footwear.",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-04-10T00:00:00Z",
  },
  {
    id: "prod-010",
    slug: "kate-spade-floral-midi-skirt",
    name: "Floral Midi Skirt",
    brand: "Kate Spade",
    category: "Bottoms",
    size: "L",
    condition: "Like New",
    price: 6200,
    description:
      "Beautiful floral midi skirt with a flattering A-line silhouette. Bold blooms in pink and green on a cream background. Worn twice — looks brand new.",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-09T00:00:00Z",
    updatedAt: "2026-04-09T00:00:00Z",
  },
  {
    id: "prod-011",
    slug: "lilly-pulitzer-jungle-print-maxi",
    name: "Jungle Print Maxi Dress",
    brand: "Lilly Pulitzer",
    category: "Dresses",
    size: "XS",
    condition: "Gently Used",
    price: 6800,
    description:
      "Flowing maxi dress in a lush jungle print with palm leaves and exotic flowers. Vibrant greens and pinks. Gently worn with lots of life left!",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-08T00:00:00Z",
    updatedAt: "2026-04-08T00:00:00Z",
  },
  {
    id: "prod-012",
    slug: "ralph-lauren-striped-bikini",
    name: "Striped Bikini Set",
    brand: "Ralph Lauren",
    category: "Swimwear",
    size: "M",
    condition: "NWT",
    price: 5800,
    description:
      "Classic striped bikini set in navy and white. Fully lined with adjustable straps. New with tags — perfect for pool or beach season!",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-07T00:00:00Z",
    updatedAt: "2026-04-07T00:00:00Z",
  },
  {
    id: "prod-013",
    slug: "lilly-pulitzer-pineapple-tee",
    name: "Pineapple Graphic Tee",
    brand: "Lilly Pulitzer",
    category: "Tops",
    size: "XL",
    condition: "NWOT",
    price: 2800,
    description:
      "Cute pineapple graphic tee in soft cotton. Relaxed fit with a fun tropical vibe. New without tags!",
    images: [],
    status: "available",
    featured: false,
    createdAt: "2026-04-06T00:00:00Z",
    updatedAt: "2026-04-06T00:00:00Z",
  },
];
